variant: fcos
version: 1.2.0
passwd:
  users:
  - name: user
    # Password is 'weakpassword'. You can get a hash for your own (hopefully
    # much stronger) password using mkpasswd --method=yescrypt
    password_hash: $y$j9T$aJ.mHatSyq7Y6A8cGmWMb1$OM0KL4KXasbKILlQvINy5dkDlJssJhgbgmmeT.Z7jp7
storage:
  files:
  # Enable SSH Password Auth for demonstration purposes.
  - path: /etc/ssh/sshd_config.d/20-enabled-passwords.conf
    mode: 0644 
    contents:
      inline: |
        PasswordAuthentication yes
